using System.Collections.Generic;

namespace FontBuilder.Core
{
    /// <summary>
    /// 固定的 208 个字符串 ID 名称（不含 R_ID_ 前缀）
    /// 对应 user_str.h 中 R_ID_STR_* 枚举与 font.tab 内容
    /// 顺序与数量固定，与 font.ini 中激活语言无关（含 4 个被注释语言）
    /// </summary>
    public static class StringIdNames
    {
        /// <summary>
        /// 固定的 208 个字符串 ID 名称列表
        /// </summary>
        public static readonly IReadOnlyList<string> All = new[]
        {
            // 语言名（18 项，含 4 个被注释语言）
            "STR_LAN_ENGLISH",
            "STR_LAN_SCHINESE",
            "STR_LAN_TCHINESE",
            "STR_LAN_JAPANESE",
            "STR_LAN_GERMAN",
            "STR_LAN_FRECH",
            "STR_LAN_RUSSIAN",
            "STR_LAN_ITALIAN",
            "STR_LAN_KOERA",
            "STR_LAN_TAI",
            "STR_LAN_HEBREW",
            "STR_LAN_DUTCH",
            "STR_LAN_UKRAINIAN",
            "STR_LAN_SPANISH",
            "STR_LAN_PORTUGUESE",
            "STR_LAN_POLISH",
            "STR_LAN_CZECH",
            "STR_LAN_TURKEY",
            // 更新
            "STR_UPDATE_START",
            "STR_UPDATE_END",
            // 通用
            "STR_COM_OFF",
            "STR_COM_ON",
            "STR_COM_OK",
            "STR_COM_CANCEL",
            "STR_COM_YES",
            "STR_COM_NO",
            "STR_COM_LOW",
            "STR_COM_MIDDLE",
            "STR_COM_HIGH",
            "STR_COM_50HZ",
            "STR_COM_60HZ",
            "STR_COM_LEVEL_0",
            "STR_COM_LEVEL_1",
            "STR_COM_LEVEL_2",
            "STR_COM_LEVEL_3",
            "STR_COM_LEVEL_4",
            "STR_COM_LEVEL_5",
            "STR_COM_LEVEL_6",
            "STR_COM_LEVEL_7",
            "STR_COM_LEVEL_8",
            "STR_COM_LEVEL_9",
            "STR_COM_P4_0",
            "STR_COM_P3_0",
            "STR_COM_P2_0",
            "STR_COM_P1_0",
            "STR_COM_P0_0",
            "STR_COM_N1_0",
            "STR_COM_N2_0",
            "STR_COM_ALWAYSON",
            "STR_COM_ECONOMIC",
            "STR_COM_NORMAL",
            "STR_COM_FINE",
            // 计时
            "STR_TIM_1MIN",
            "STR_TIM_2MIN",
            "STR_TIM_3MIN",
            "STR_TIM_5MIN",
            "STR_TIM_10MIN",
            "STR_TIM_2SEC",
            "STR_TIM_3SEC",
            "STR_TIM_5SEC",
            "STR_TIM_10SEC",
            "STR_TIM_30SEC",
            // 照片数量
            "STR_PHOTO_NUM_3",
            "STR_PHOTO_NUM_5",
            // 设置菜单
            "STR_SET_SETTING",
            "STR_SET_VIDEO",
            "STR_SET_PHOTO",
            "STR_SET_PLAY",
            "STR_SET_MUSIC",
            "STR_SET_GAME",
            "STR_SET_LANGUAGE",
            "STR_SET_PRINT_DENSITY",
            "STR_SET_PRINT_MODE",
            "STR_SET_DATETIME",
            "STR_SET_VOLUME",
            "STR_SET_VIDEO_RESOLUTION",
            "STR_SET_CAMERA_RESOLUTION",
            "STR_SET_FORMAT",
            "STR_SET_AUTOOFF",
            "STR_SET_SCREEN_SAVERS",
            "STR_SET_LOOPRECORD",
            "STR_SET_FREQUENCY",
            "STR_SET_DEFAULT_SETTING",
            "STR_SET_VERSION",
            "STR_SET_PRINT_GRAY",
            "STR_SET_PRINT_DOT",
            // 提示
            "STR_TIPS_PRINTING",
            "STR_TIPS_NO_PAPER",
            "STR_TIPS_OVER_HEAT",
            "STR_TIPS_SDC_NULL",
            "STR_TIPS_SDC_FULL",
            "STR_TIPS_NO_FILES",
            "STR_TIPS_NO_POWER",
            "STR_TIPS_PLEASE_WAITING",
            "STR_TIPS_FMT_SUCCESS",
            "STR_TIPS_FMT_FAIL",
            "STR_TIPS_DELETECUR",
            // 设置（续）
            "STR_SET_AUDIOMODE",
            "STR_SET_USBMASS",
            "STR_SET_USBCAM",
            "STR_SET_TIMEPHOTO",
            "STR_SET_MOREPHOTO",
            "STR_SET_VIDEOROTATE",
            "STR_SET_MOTIONDET",
            "STR_SET_AUDIOREC",
            "STR_SET_TIMESTRAMP",
            "STR_SET_FILLIGHT",
            "STR_IR_AUTO",
            "STR_SET_GSENSOR",
            "STR_SET_PARKMODE",
            "STR_SET_FASTVIEW",
            "STR_SET_DELETECUR",
            "STR_SET_DELETEALL",
            "STR_SET_LOCKCUR",
            "STR_SET_LOCKALL",
            "STR_SET_UNLOCKCUR",
            "STR_SET_UNLOCKALL",
            "STR_SET_LOCKED",
            "STR_SET_LOCK",
            "STR_SET_DELETE",
            "STR_SET_PLAYMODE",
            "STR_SET_REPEATALL",
            "STR_SET_REPEATRAD",
            "STR_SET_REPEATSIG",
            "STR_SET_AUDIOPLAY",
            "STR_SET_THUMBNAIL",
            "STR_SET_BEEPSOUND",
            "STR_SET_QUALITY",
            "STR_SET_PROMT",
            // 分辨率
            "STR_RES_240P",
            "STR_RES_480P",
            "STR_RES_480FHD",
            "STR_RES_720P",
            "STR_RES_1024P",
            "STR_RES_1080P",
            "STR_RES_1080FHD",
            "STR_RES_1440P",
            "STR_RES_3024P",
            "STR_RES_720P_SHORT",
            "STR_RES_1080P_SHORT",
            "STR_RES_QVGA",
            "STR_RES_VGA",
            "STR_RES_HD",
            "STR_RES_FHD",
            "STR_RES_48M",
            "STR_RES_40M",
            "STR_RES_24M",
            "STR_RES_20M",
            "STR_RES_18M",
            "STR_RES_16M",
            "STR_RES_12M",
            "STR_RES_10M",
            "STR_RES_8M",
            "STR_RES_5M",
            "STR_RES_3M",
            "STR_RES_2M",
            "STR_RES_1M",
            // SD/文件/格式/电源
            "STR_SDC_NULL1",
            "STR_SDC_ERROR",
            "STR_FIL_LOCKED",
            "STR_FMT_ING",
            "STR_FMT_RESET",
            "STR_FMT_FORMAT",
            "STR_FMT_DELETE",
            "STR_PWR_LOW",
            "STR_PWR_BACKLOW",
            "STR_PWR_CHARGELOW",
            // ISP
            "STR_ISP_WHITEBL",
            "STR_ISP_ISO",
            "STR_ISP_ANTISHANK",
            "STR_ISP_AUTO",
            "STR_ISP_SOFT",
            "STR_ISP_STRONG",
            "STR_ISP_SUNLIGHT",
            "STR_ISP_CLOUDY",
            "STR_ISP_TUNGSTEN",
            "STR_ISP_FLUORESCENT",
            "STR_ISP_BLACKWHITE",
            "STR_ISP_SEPIA",
            "STR_ISP_ISO100",
            "STR_ISP_ISO200",
            "STR_ISP_ISO400",
            "STR_ISP_WDR",
            "STR_ISP_EXPOSURE",
            // 通用（续）
            "STR_COM_SUCCESS",
            "STR_COM_FAILED",
            "STR_COM_LIGHTING_FORM",
            // 游戏提示
            "STR_GAME_TIPS_GAME_OVER",
            "STR_GAME_TIPS_START",
            "STR_GAME_TIPS_PLAY_AGAIN",
            "STR_GAME_TIPS_CONTINUE",
            "STR_GAME_TIPS_EXIT",
            // 录像/亮度
            "STR_COM_VIDEOREC_NORMAL",
            "STR_COM_VIDEOREC_SLOW",
            "STR_COM_VIDEOREC_FAST",
            "STR_COM_LCD_BRIGHTNESS",
            // 游戏
            "STR_GAME_NES",
            "STR_GAME_001",
            "STR_GAME_002",
            "STR_GAME_003",
            "STR_GAME_004",
            "STR_GAME_005",
            "STR_GAME_006",
            "STR_GAME_007",
            // SD 提示（续）
            "STR_TIPS_SPI_FULL",
            "STR_TIPS_INT_SDC",
            "STR_TIPS_SDC_INT",
            "STR_TIPS_SDC_MOV"
        };

        /// <summary>
        /// 字符串总数（固定 208）
        /// </summary>
        public const int Count = 208;
    }
}
